### ISSUE TITLE
Tower Support

### ISSUE THREAD

**Issue by tgandee79** [stevenharman/git_tracker#20]
I had to `PATH="$PATH:/usr/local/bin"` to the top of the hook file for Tower Git client to recognize the `git-tracker` command.

**Comment by stevenharman** [comment]
I believe this is a problem with @gittower and the `PATH` they've configured for their Git client. The [hooks are called from the Tower process environment](https://www.git-tower.com/help/mac/faq-and-tips/faq/hook-scripts), which has it's own configured `PATH`.

What I find interesting is that they don't seem to include `/usr/local/bin` on that `PATH`. That is a pretty standard place for binaries to live on a *nix system. Which is why that's where `homebrew` will symlink binaries by default. e.g., `brew install git-tracker` will symlink a `git-tracker binary to `/usr/local/bin/git-tracker`, and when the hook calls `git tracker` that binary is resolved due to the symlink + `PATH`.

There's not much we can do on the `git-tracker` side. Maybe add a little blurb to the `README` to explain the workaround? Other than that, I'd suggest opening an issue with Tower to see if they can include `/usr/local/bin` in the `PATH` for their client environment.

**Comment by tgandee79** [comment]
thanks Steven.
